### ISSUE TITLE
Adding exclusions

### ISSUE THREAD

**Issue by afider** [chloi/grunt-surge#2]
Could you please implement the ability to add exceptions like that
`exclusions: ['path/to/source/folder/**/.DS_Store', 'path/to/source/folder/**/Thumbs.db', 'path/to/dist/tmp']`

**Comment by kennethormandy** [comment]
Hey! Thanks for opening an issue. Surge already ignores `.` files, and you can expand on this list by creating a `.surgeignore` file. It works like a `.gitignore` file.

Does that work for you right now?

**Comment by afider** [comment]
Thanks, yes, it works, but I would like to exclude the whole directories.

**Comment by kennethormandy** [comment]
Hey @afider,

You can also use the `.surgeignore` for directories like with `.gitignore`. For example, if you wanted to ignore a directory called `psd/`, just add it:

```
psd/
```

Let me know if that works for you.

**Comment by kennethormandy** [comment]
Hey @afider,

You can also use the `.surgeignore` for directories like with `.gitignore`. For example, if you wanted to ignore a directory called `psd/`, just add it:

```
psd/
```

Let me know if that works for you.

**Comment by afider** [comment]
I created a file `.surgeignore`  with this content  `tmp/` but all the files in this directory have been sent to the server too. Can you give me an example for testing wich works, maybe I'm doing something wrong.

**Comment by kennethormandy** [comment]
Hm, that should have done the trick. Was it something you had already published, that you then added to the `.surgeignore` file? It might not ignore previously published things.

Mind also giving me the version of your OS and Node? Thanks!

**Comment by afider** [comment]
No, it was not published previously, I created a new directory for testing that.

OS Windows 8.1
Node v0.10.36

**Comment by kennethormandy** [comment]
Thanks, it might be something Windows-specific then. We’ll look into it here: https://github.com/sintaxi/surge/issues/73
