### ISSUE TITLE
Possible issue with zsh? Task just hangs

### ISSUE THREAD

**Issue by jforaker** [chloi/grunt-surge#3]
I am using zsh / https://github.com/robbyrussell/oh-my-zsh  and it seems the grunt command just hangs and does nothing.  I can't even control-c to stop it.  Any ideas?

**Comment by kennethormandy** [comment]
Not really, to be honest, but thanks for reporting it! Mind sharing what OS and version, version of Node, and version of grunt-surge you are using?

**Comment by jforaker** [comment]
Sure...

```
node v0.12.4
OSX 10.10.3 (14D136)
"grunt-surge": "^0.6.2",
grunt-cli v0.1.13
grunt v0.4.5
```
